### ISSUE TITLE
Crash on server 1.10.2 Forge

### ISSUE THREAD

**Issue by dearvoodoo** [derfl007/Road-Mod#10]
Hello!

I have a problem with your mod. It crashes my server at startup.
Here is the crash report [http://pastebin.com/UHnAJrqL](http://pastebin.com/UHnAJrqL)

**Mod version**: Roads-1.2.jar
**Forge Version**: 12.18.3.2185
**Minecraft version**: 1.10.2

Thanks

EDIT: Ho yes and for information the launcher works very well and the solo too.

**Comment by dearvoodoo** [comment]
Can you tell me when the problem is solved please? thank you

**Comment by derfl007** [comment]
I think I just found the error, I'll tell you when the new version is up

**Comment by derfl007** [comment]
Newest version is now downloadable! 
Links: https://derfl007.jimdo.com/downloads/
(Click on download newest under MC 1.10)
